/*
 * generated by Xtext 2.12.0
 */
package com.softtek.uc


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class UcsRuntimeModule extends AbstractUcsRuntimeModule {
}
