/*
 * generated by Xtext 2.12.0
 */
package com.softtek.uc


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class UcsStandaloneSetup extends UcsStandaloneSetupGenerated {

	def static void doSetup() {
		new UcsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
